### PR TITLE
Added my solutions for Python questions (SQL questions left). Deleted old MySQL doc and added new one.

### PR DESCRIPTION
**Pull request by SuketuPatni**

### CODE REVIEW

**Comment by kry0sc0pic** [comment]
can u rename files so they don't overwrite mine lol.

**Comment by SuketuPatni** [comment]
> can u rename files so they don't overwrite mine lol
Whoops, sorry bruv, will do so tomorrow 👍

**Comment by SuketuPatni** [comment]
changed filenames :+1:

**Review by kry0sc0pic — APPROVED** [review]
Siu

**Pull request merged**
